const DATA = {
    LOAD: 'LOAD_DATA',
    SUCCESS: 'FETCHED_DATA_SUCCESS',
    ERROR: 'FETCHED_DATA_ERROR',
};

const PRODUCTBYIDDATA = {
    LOAD: 'FETCH_PRODUCT_BY_ID',
    SUCCESS: 'FETCH_PRODUCT_BY_ID_SUCCEESS',
    ERROR: 'FETCH_PRODUCT_BY_ID_ERROR'
};

const GEOLOCATION = {
    LOAD: 'GEOLOCATION',
    SUCCESS: 'GEOLOCATION_SUCCEESS',
    ERROR: 'GEOLOCATION_ERROR'
};

const CREATEORDER = {
    LOAD: 'CREATEORDER',
    SUCCESS: 'CREATEORDER_SUCCEESS',
    ERROR: 'CREATEORDER_ERROR'
};

const GETCLIENTSECRET = {
    LOAD: 'GETCLIENTSECRET',
    SUCCESS: 'GETCLIENTSECRET_SUCCEESS',
    ERROR: 'GETCLIENTSECRET_ERROR'
};

const GETORDERHISTORY = {
    LOAD: 'GETORDERHISTORY',
    SUCCESS: 'GETORDERHISTORY_SUCCEESS',
    ERROR: 'GETORDERHISTORY_ERROR'
};

const GETSINGLEORDERDETAILS = {
    LOAD: 'GETSINGLEORDERDETAILS',
    SUCCESS: 'GETSINGLEORDERDETAILS_SUCCEESS',
    ERROR: 'GETSINGLEORDERDETAILS_ERROR'
};

export { DATA, PRODUCTBYIDDATA, GEOLOCATION, CREATEORDER, GETCLIENTSECRET, GETORDERHISTORY, GETSINGLEORDERDETAILS };
